export const routes = {
  home: "/",
  company: "/company",
  aboutLegacy: "/about",
  collections: "/collections",
  collectionsDetailPattern: "/collections/:slug",
  collectionDetail: (slug: string) => `/collections/${slug}`,
  products: "/products",
  productsLegacy: "/catalog",
  productsDetailPattern: "/products/:slug",
  productDetail: (slug: string) => `/products/${slug}`,
  productsDetailLegacyPattern: "/catalog/:slug",
  productDetailLegacy: (slug: string) => `/catalog/${slug}`,
  projects: "/projects",
  projectDetailPattern: "/projects/:slug",
  projectDetail: (slug: string) => `/projects/${slug}`,
  downloads: "/downloads",
  downloadsLegacy: "/for-architects",
  faq: "/faq",
  contacts: "/contacts",
  requestProject: "/request-project",
  materials: "/materials",
  privacy: "/privacy",
  cookies: "/cookies",
  consent: "/consent",
  terms: "/terms",
} as const;

export const legacyToCanonical = {
  "/catalog": routes.products,
  "/about": routes.company,
  "/for-architects": routes.downloads,
} as const;
