export const sitemapConfig = {
  siteUrl: process.env.SITE_URL || "https://ston.ru",
  staticPaths: [
    "/",
    "/company",
    "/collections",
    "/products",
    "/projects",
    "/downloads",
    "/materials",
    "/for-objects",
    "/faq",
    "/contacts",
    "/request-project",
    "/privacy",
    "/cookies",
    "/consent",
    "/terms",
  ],
  collectionSlugs: ["bollards-core"],
  productSlugs: [
    "bollard-400-cast-stone",
    "bollard-600-cast-stone",
    "bollard-600-natural-stone",
    "bollard-800-cast-stone",
  ],
  textureSlugs: ["smooth", "stone"],
  downloadCategories: ["catalogue", "bim"],
};
