export const sitemapConfig = {
  siteUrl: process.env.SITE_URL || "https://ston.ru",
  staticPaths: [
    "/",
    "/company",
    "/collections",
    "/products",
    "/projects",
    "/downloads",
    "/materials",
    "/for-objects",
    "/faq",
    "/contacts",
    "/request-project",
    "/privacy",
    "/cookies",
    "/consent",
    "/terms",
  ],
  collectionSlugs: ["bollards-core"],
  productSlugs: [],
  nestedProductPaths: [
    "/izdeliya/vozduh/feya",
    "/izdeliya/vozduh/mengir",
    "/izdeliya/zemlya/fokus",
    "/izdeliya/zemlya/mayak",
  ],
  textureSlugs: ["natural-stone", "composite", "special-materials"],
  downloadCategories: ["catalogue", "bim", "support"],
};
